export const articles = [
  {
    id: 1,
    author: "Brian Jenney",
    title: "The Upcoming “Robotaxi Day” Could Make Or Break Tesla",
    description: "Google’s good news and bad news came very suddenly.",
    tag: "Tech",
    responses: 23,
    claps: 1.2,
    publishDate: "16-06-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 2,
    author: "Alex Smith",
    title: "AI in Healthcare: Transforming the Future",
    description: "How artificial intelligence is revolutionizing healthcare.",
    tag: "Health",
    responses: 12,
    claps: 3.5,
    publishDate: "12-05-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 3,
    author: "Jessica Brown",
    title: "The Economics of Climate Change",
    description: "Exploring the financial impacts of global warming.",
    tag: "Economics",
    responses: 45,
    claps: 2.3,
    publishDate: "10-04-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 4,
    author: "Michael Davis",
    title: "Cryptocurrency: A Double-Edged Sword",
    description: "The risks and rewards of investing in cryptocurrency.",
    tag: "Finance",
    responses: 30,
    claps: 4.0,
    publishDate: "01-06-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 5,
    author: "Sarah Wilson",
    title: "The Future of Remote Work",
    description: "How remote work is shaping the global job market.",
    tag: "Business",
    responses: 18,
    claps: 2.8,
    publishDate: "15-06-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 6,
    author: "David Lee",
    title: "The Rise of Electric Vehicles",
    description: "Why electric vehicles are becoming more popular.",
    tag: "Automotive",
    responses: 25,
    claps: 3.1,
    publishDate: "05-05-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 7,
    author: "Emma Martinez",
    title: "Advancements in Quantum Computing",
    description: "The potential and challenges of quantum computing.",
    tag: "Technology",
    responses: 22,
    claps: 4.5,
    publishDate: "20-06-2024",
    staffPics: true,
    profileImage: "profile-2.jpg"
  },
  {
    id: 8,
    author: "John Thompson",
    title: "Mental Health Awareness",
    description: "The importance of mental health in the modern world.",
    tag: "Health",
    responses: 40,
    claps: 3.7,
    publishDate: "25-05-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 9,
    author: "Olivia Perez",
    title: "Sustainable Fashion: A New Trend",
    description: "How sustainability is influencing the fashion industry.",
    tag: "Fashion",
    responses: 15,
    claps: 2.9,
    publishDate: "30-06-2024",
    staffPics: true,
    profileImage: "profile-2.jpg"
  },
  {
    id: 10,
    author: "James Clark",
    title: "The Evolution of Social Media",
    description: "The changes and future trends in social media platforms.",
    tag: "Social Media",
    responses: 50,
    claps: 4.2,
    publishDate: "08-06-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 11,
    author: "Nancy Green",
    title: "The Future of Renewable Energy",
    description: "Exploring new advancements in renewable energy.",
    tag: "Energy",
    responses: 32,
    claps: 3.9,
    publishDate: "15-07-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 12,
    author: "Thomas Parker",
    title: "Smart Cities: Urban Planning for the Future",
    description: "How smart cities are changing urban life.",
    tag: "Urban Planning",
    responses: 18,
    claps: 4.1,
    publishDate: "22-07-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 13,
    author: "Linda Martin",
    title: "The Impact of 5G Technology",
    description: "How 5G technology is set to revolutionize connectivity.",
    tag: "Technology",
    responses: 27,
    claps: 4.4,
    publishDate: "05-08-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 14,
    author: "Daniel Rodriguez",
    title: "Blockchain Beyond Cryptocurrency",
    description: "Exploring other applications of blockchain technology.",
    tag: "Tech",
    responses: 20,
    claps: 3.0,
    publishDate: "12-08-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 15,
    author: "Patricia Johnson",
    title: "Cybersecurity in the Age of AI",
    description: "The challenges of ensuring cybersecurity with AI.",
    tag: "Technology",
    responses: 35,
    claps: 4.3,
    publishDate: "19-08-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 16,
    author: "Richard White",
    title: "The Future of Space Exploration",
    description: "What’s next in humanity’s quest to explore space?",
    tag: "Space",
    responses: 25,
    claps: 4.6,
    publishDate: "28-08-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 17,
    author: "Karen Taylor",
    title: "The Psychology of Consumer Behavior",
    description: "Understanding why we buy what we buy.",
    tag: "Psychology",
    responses: 29,
    claps: 3.5,
    publishDate: "05-09-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 18,
    author: "Edward Miller",
    title: "The Role of Big Data in Business",
    description: "How businesses are leveraging big data.",
    tag: "Business",
    responses: 22,
    claps: 3.8,
    publishDate: "12-09-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 19,
    author: "Barbara Garcia",
    title: "The Evolution of Artificial Intelligence",
    description: "From concept to reality: The journey of AI.",
    tag: "Tech",
    responses: 42,
    claps: 4.7,
    publishDate: "21-09-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 20,
    author: "Susan Martinez",
    title: "The Impact of Social Media on Society",
    description: "Analyzing the positive and negative effects of social media.",
    tag: "Social Media",
    responses: 36,
    claps: 4.0,
    publishDate: "01-10-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 21,
    author: "George Thompson",
    title: "The Future of Online Education",
    description: "How online education is transforming learning.",
    tag: "Education",
    responses: 28,
    claps: 3.9,
    publishDate: "10-10-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 22,
    author: "Betty Adams",
    title: "The Evolution of E-Commerce",
    description: "Trends and future directions in e-commerce.",
    tag: "E-Commerce",
    responses: 31,
    claps: 3.7,
    publishDate: "20-10-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 23,
    author: "Chris Johnson",
    title: "The Rise of Smart Home Technology",
    description: "How smart home devices are changing our lives.",
    tag: "Tech",
    responses: 19,
    claps: 4.2,
    publishDate: "29-10-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 24,
    author: "Deborah Nelson",
    title: "The Role of Genetics in Medicine",
    description: "How genetics is shaping modern medicine.",
    tag: "Health",
    responses: 15,
    claps: 3.4,
    publishDate: "05-11-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 25,
    author: "James Harris",
    title: "The Future of Financial Technology",
    description: "Exploring innovations in fintech.",
    tag: "Finance",
    responses: 24,
    claps: 4.1,
    publishDate: "15-11-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 26,
    author: "Rebecca Lewis",
    title: "The Impact of Automation on Jobs",
    description: "How automation is transforming the job market.",
    tag: "Economics",
    responses: 33,
    claps: 3.8,
    publishDate: "25-11-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 27,
    author: "Anthony Walker",
    title: "The Future of Augmented Reality",
    description: "How AR is changing the way we interact with the world.",
    tag: "Tech",
    responses: 30,
    claps: 4.3,
    publishDate: "05-12-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 28,
    author: "Laura Young",
    title: "The Role of AI in Financial Services",
    description: "How AI is transforming the finance industry.",
    tag: "Finance",
    responses: 21,
    claps: 4.0,
    publishDate: "15-12-2024",
    staffPics: false,
    profileImage: "profile-2.jpg"
  },
  {
    id: 29,
    author: "Steven King",
    title: "The Future of Biotechnology",
    description: "Exploring new advancements in biotechnology.",
    tag: "Health",
    responses: 26,
    claps: 3.9,
    publishDate: "25-12-2024",
    staffPics: true,
    profileImage: "profile-1.jpg"
  },
  {
    id: 30,
    author: "Amy Hall",
    title: "The Evolution of Renewable Energy",
    description: "The latest developments in renewable energy.",
    tag: "Energy",
    responses: 37,
    claps: 4.5,
    publishDate: "01-01-2025",
    staffPics: false,
    profileImage: "profile-2.jpg"
  }
];
