import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../layouts/Header";
import Notifications from "@/components/Notifications";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Medium Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <Notifications />
        <div className="dashboard">
          <div className="container max-w-7xl m-auto py-5">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
